base/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("contact/", views.contact, name="contact"),
    path("about/", views.about, name="about"),
    path("faq/", views.faq, name="faq"),
    path("error_404/", views.error_404, name="error_404"),
]

listing/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.listing, name="listing"),
    path("<int:listing_id>/", views.listing_details, name="listing_details"),
    path("category/", views.category, name="category"),
    path("add/", views.add_listing, name="add_listing"),
    path("edit/<int:listing_id>", views.edit_listing, name="edit_listing"),
    path("delete/<int:listing_id>", views.delete_listing, name="delete_listing"),
    path("get_subcategories/", views.get_subcategories, name="get_subcategories"),
    path(
        "get_all_subcategories/",
        views.get_all_subcategories,
        name="get_all_subcategories",
    ),
]

listygo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from .views import logout_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include("blog.urls")),
    path("listing/", include("listing.urls")),
    path("user/", include("user.urls")),
    path("", include("base.urls")),
    path("accounts/logout/", logout_view, name="account_logout"),
    path("accounts/", include("allauth.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

listing/models.py
from decimal import Decimal

from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator, RegexValidator
from django.db import models
from django.db.models import Avg
from PIL import Image

APPROVED = "A"
PENDING = "P"
DENIED = "D"

LISTING_IMAGE_SIZE = (670, 390)

STATUS_CHOICES = [
    (APPROVED, "Approved"),
    (PENDING, "Pending"),
    (DENIED, "Denied"),
]

phone_regex = RegexValidator(
    regex=r"^\d{5,10}$",
    message="Invalid phone number",
)


def validate_price(value):
    if not isinstance(value, (int, float, Decimal)):
        raise ValidationError("Price should be numeric")


class ListingAmenities(models.Model):
    title = models.CharField(max_length=1000, help_text="Enter the amenities title")
    description = models.CharField(
        max_length=2000, help_text="Enter the amenities description"
    )
    image = models.ImageField(
        upload_to="amenities/images", help_text="Upload the amenities image(80*80)"
    )
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def __str__(self) -> str:
        return str(self.title)

    class Meta:
        verbose_name_plural = "Property Amenties"
        ordering = ("title",)


class ListingCategory(models.Model):
    name = models.CharField(max_length=1000, help_text="Enter the category name")
    logo = models.ImageField(
        upload_to="listing/images/",
        help_text="Upload the category logo(80*80)",
        verbose_name="Category Logo",
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return str(self.name)

    def total_listing(self):
        return self.category_listing.filter(status=APPROVED).count()

    class Meta:
        verbose_name_plural = "Property Categories"
        ordering = ("name",)


class ListingSubCategory(models.Model):
    category = models.ForeignKey(
        ListingCategory,
        on_delete=models.CASCADE,
        related_name="subcategory",
        help_text="Select the category",
    )
    name = models.CharField(max_length=1000, help_text="Enter the subcategory name")
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    def __str__(self) -> str:
        return str(self.name)

    def total_listing(self):
        return self.subcategory_listing.count()

    class Meta:
        verbose_name_plural = "Property SubCategories"
        ordering = ("name",)


class ListingPost(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, help_text="Author who submitted the listing"
    )
    business_name = models.CharField(
        max_length=1000,
        help_text="Enter the property name",
        verbose_name="Property name",
    )
    category = models.ForeignKey(
        ListingCategory,
        related_name="category_listing",
        help_text="Select the property category",
        blank=True,
        on_delete=models.CASCADE,
    )
    subcategory = models.ManyToManyField(
        ListingSubCategory,
        related_name="subcategory_listing",
        help_text="Select the property subcategories",
        verbose_name="Categories & Subcategories",
    )
    status = models.CharField(
        max_length=1,
        choices=STATUS_CHOICES,
        default=PENDING,
        help_text="Choose whether to display on site or not",
        blank=True,
        null=True,
    )

    description = models.TextField(help_text="Enter the property description")
    location = models.CharField(
        max_length=1000,
        help_text=" Enter the location (building, tool, chowk etc) ",
        blank=True,
        null=True,
    )
    street = models.CharField(
        max_length=1000,
        help_text=" Enter the street address (street name, area etc)",
    )

    city = models.CharField(
        max_length=1000,
        help_text=" Enter the city name",
    )

    state = models.CharField(
        max_length=1000,
        help_text="Enter the province name",
        verbose_name="Province",
        blank=True,
        null=True,
    )

    latitude = models.CharField(
        max_length=15,
        help_text="Enter the latitude",
        blank=True,
        null=True,
    )

    longitude = models.CharField(
        max_length=15,
        help_text="Enter the longitude",
        blank=True,
        null=True,
    )

    email = models.EmailField(help_text="Enter the email")

    main_phone = models.CharField(validators=[phone_regex], max_length=17)
    mobile_phone = models.CharField(validators=[phone_regex], max_length=17, blank=True)

    image1 = models.ImageField(
        upload_to="listing/images/", help_text="Upload the listing image(670*390)"
    )
    image2 = models.ImageField(
        upload_to="listing/images/",
        help_text="Upload the listing image(670*390)",
        blank=True,
        null=True,
    )
    image3 = models.ImageField(
        upload_to="listing/images/",
        help_text="Upload the listing image(670*390)",
        blank=True,
        null=True,
    )
    image4 = models.ImageField(
        upload_to="listing/images/",
        help_text="Upload the listing image(670*390)(Available for only paid listing)",
        blank=True,
        null=True,
    )
    image5 = models.ImageField(
        upload_to="listing/images/",
        help_text="Upload the listing image(670*390)(Available for only paid listing)",
        blank=True,
        null=True,
    )
    image6 = models.ImageField(
        upload_to="listing/images/",
        help_text="Upload the listing image(670*390)(Available for only paid listing)",
        blank=True,
        null=True,
    )

    amenities = models.ManyToManyField(
        ListingAmenities,
        help_text="Select the property amenities",
        blank=True,
    )
    price = models.DecimalField(
        help_text="Enter the property price",
        max_digits=10,
        decimal_places=2,
        validators=[MinValueValidator(Decimal("1")), validate_price],
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        image_fields = [
            self.image1,
            self.image2,
            self.image3,
            self.image4,
            self.image5,
            self.image6,
        ]
        for image_field in image_fields:
            if image_field:
                img = Image.open(image_field.path)
                width, height = img.size
                aspect = width / float(height)

                ideal_width, ideal_height = LISTING_IMAGE_SIZE
                ideal_aspect = ideal_width / float(ideal_height)

                if aspect > ideal_aspect:
                    # Then crop the left and right edges:
                    new_width = int(ideal_aspect * height)
                    offset = (width - new_width) / 2
                    resize = (offset, 0, width - offset, height)
                else:
                    # ... crop the top and bottom:
                    new_height = int(width / ideal_aspect)
                    offset = (height - new_height) / 2
                    resize = (0, offset, width, height - offset)

                img = img.crop(resize).resize(
                    (ideal_width, ideal_height), Image.Resampling.LANCZOS
                )
                img.save(image_field.path)

    def average_rating(self):
        """Return average rating of a product"""
        return self.reviews.filter().aggregate(rating=Avg("rating")).get("rating")

    def __str__(self) -> str:
        return str(self.business_name)

    class Meta:
        verbose_name_plural = "Properties"
        ordering = ("-created_at",)


class PropertyContact(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, help_text="Author who created the review"
    )
    listing = models.ForeignKey(
        ListingPost,
        on_delete=models.CASCADE,
        related_name="contacts",
        help_text="Select the property",
    )
    subject = models.CharField(max_length=255, help_text="Subject of the message")
    message = models.TextField(help_text="Contact Description")
    submit_date = models.DateField(auto_now_add=True)

    def __str__(self) -> str:
        return str(self.subject)

    class Meta:
        verbose_name_plural = "Properties Contacts"
        ordering = ("-submit_date",)


class ListingReview(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, help_text="Author who created the review"
    )
    listing = models.ForeignKey(
        ListingPost,
        on_delete=models.CASCADE,
        related_name="reviews",
        help_text="Select the property",
    )

    title = models.CharField(help_text="Enter the title of your review", max_length=500)
    description = models.TextField(help_text="Enter the description of the review")
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    rating = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)],
        help_text="Enter the rating of the listing between 1 and 5",
    )

    def __str__(self) -> str:
        return f"{str(self.listing)}_{str(self.user)}"

    class Meta:
        verbose_name_plural = "Property Reviews"
        unique_together = ("user", "listing")
        ordering = ("-created_at",)

listing/forms.py
from django import forms
from tinymce.widgets import TinyMCE

from .models import (
    ListingCategory,
    ListingPost,
    ListingReview,
    ListingSubCategory,
    PropertyContact,
)


class ListingForm(forms.Form):
    SORT_CHOICES = [
        ("0", "Sort By"),
        ("1", "Recommended"),
        ("2", "Newest"),
        ("3", "Most Reviewed"),
        ("4", "Top Rated"),
        ("5", "A to Z"),
    ]

    business_name = forms.CharField(
        max_length=255,
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "Enter properties name...",
            }
        ),
    )
    business_location = forms.CharField(
        max_length=255,
        required=False,
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "Enter location, street, area or city...",
            }
        ),
    )
    business_category = forms.ModelChoiceField(
        queryset=ListingCategory.objects.all(),
        required=False,
        empty_label="Choose Category",
        widget=forms.Select(attrs={"class": "select2"}),
    )
    business_subcategory = forms.ModelChoiceField(
        queryset=ListingSubCategory.objects.all(),
        required=False,
        empty_label="Choose Subcategory",
        widget=forms.Select(attrs={"class": "select2"}),
    )
    business_sort = forms.ChoiceField(
        choices=SORT_CHOICES,
        required=False,
        widget=forms.Select(attrs={"class": "select2"}),
    )

    def clean(self):
        cleaned_data = super().clean()
        category_id = cleaned_data.get("business_category")
        subcategory_id = cleaned_data.get("business_subcategory")

        if category_id is None:
            if "business_category" in self._errors:
                del self._errors["business_category"]

        if subcategory_id is None:
            if "business_subcategory" in self._errors:
                del self._errors["business_subcategory"]

        return cleaned_data


class ListingReviewForm(forms.ModelForm):
    class Meta:
        model = ListingReview
        fields = ["title", "description", "rating"]
        widgets = {
            "title": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "", "required": True}
            ),
            "description": forms.Textarea(
                attrs={
                    "class": "textarea form-control",
                    "cols": 20,
                    "rows": 7,
                    "required": True,
                }
            ),
            "rating": forms.NumberInput(
                attrs={"class": "form-control", "required": True}
            ),
        }


class PropertyContactForm(forms.ModelForm):
    class Meta:
        model = PropertyContact
        fields = ["subject", "message"]

        widgets = {
            "subject": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "",
                    "data-error": "Subject field is required",
                },
            ),
            "message": forms.Textarea(
                attrs={
                    "class": "textarea form-control",
                    "cols": "20",
                    "rows": "7",
                    "placeholder": "",
                    "data-error": "Message field is required",
                }
            ),
        }


class ListingPostForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ListingPostForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.required = True
        self.fields["image2"].required = False
        self.fields["image3"].required = False
        self.fields["image4"].required = False
        self.fields["image5"].required = False
        self.fields["image6"].required = False
        self.fields["amenities"].required = False
        self.fields["status"].required = False

        if self.instance and self.instance.pk:
            self.fields["subcategory"].queryset = ListingSubCategory.objects.filter(
                category=self.instance.category
            )
        if self.instance and self.instance.pk and self.instance.image1:
            self.fields["image1"].required = False

    class Meta:
        model = ListingPost
        fields = "__all__"
        widgets = {
            "user": forms.Select(attrs={"class": "form-control"}),
            "business_name": forms.TextInput(attrs={"class": "form-control"}),
            "category": forms.Select(
                attrs={
                    "class": "form-control",
                    "style": "padding: 0 10px; height:50px;",
                }
            ),
            "subcategory": forms.SelectMultiple(attrs={"class": "form-control"}),
            "description": TinyMCE(attrs={"class": "form-control"}),
            "location": forms.TextInput(attrs={"class": "form-control"}),
            "street": forms.TextInput(attrs={"class": "form-control"}),
            "city": forms.TextInput(attrs={"class": "form-control"}),
            "state": forms.TextInput(attrs={"class": "form-control"}),
            "latitude": forms.TextInput(attrs={"class": "form-control"}),
            "longitude": forms.TextInput(attrs={"class": "form-control"}),
            "email": forms.EmailInput(attrs={"class": "form-control"}),
            "main_phone": forms.TextInput(attrs={"class": "form-control"}),
            "mobile_phone": forms.TextInput(attrs={"class": "form-control"}),
            "image1": forms.FileInput(
                attrs={"class": "form-control ", "id": "img-upload1"}
            ),
            "image2": forms.FileInput(
                attrs={"class": "form-control ", "id": "img-upload2"}
            ),
            "image3": forms.FileInput(
                attrs={"class": "form-control ", "id": "img-upload3"}
            ),
            "amenities": forms.SelectMultiple(attrs={"class": "form-control"}),
            "price": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Enter the price"}
            ),
        }

listing/templates/listing/add_listing.html
{% extends "base.html" %}

{% load static %}


{% block title %}
<title>Birauta Real Estate and Housing Pvt Ltd | Add Property</title>
{% endblock title %}

{% block main %}

<!-- Inne Page Banner Area Start Here -->
<section class="inner-page-banner bg-common inner-page-top-margin overlay-dark-40"
  data-bg-image="{{ hero_image.image.url }}">
  <div class="container">
    <div class="row">
      <div class="col-12">
        <div class="breadcrumbs-area">
          <h1>Submit Property</h1>
          <ul>
            <li>
              <a href="{% url 'home' %}">Home</a>
            </li>
            <li>Add Property</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Inne Page Banner Area End Here -->
<!-- Add Listing Area Start Here -->
<section class="padding-top-6 padding-bottom-7 bg--accent">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <form class="listing-form" method="post" id="add_form" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="inner-box">
            <h3 class="inner-item-heading2">General Information</h3>
            <div class="row">
              <div class="col-12">
                <label>Property Name</label>
                <div class="form-group">
                  {{form.business_name}}
                </div>
              </div>
              <div class="col-md-6">
                <label>Category</label>
                <div class="form-group">
                 {{form.category}}
                </div>
              </div>
              <div class="col-md-6">
                <label>Subcategory</label>
                <div class="form-group">
                 {{form.subcategory}}
                </div>
              </div>
           
              <div class="col-12">
                <label>Description</label>
                <div class="form-group">
                    {{ form.description }}
                    {% if form.description.errors %}
                        <div class="text-danger">
                            {{ form.description.errors }}
                        </div>
                    {% endif %}
                </div>
            </div>
            </div>
          </div>
          <div class="inner-box">
            <h3 class="inner-item-heading2">Add Location</h3>
            <div class="row">
              <div class="col-sm-6">
                <label>Address (Building, Floor, Suite, Number etc)</label>
                <div class="form-group">
                  {{form.location}}
                </div>
              </div>
              <div class="col-sm-6">
                <label>Street Address (Street Name, Area etc)</label>
                <div class="form-group">
                  {{form.street}}
                </div>
              </div>
              <div class="col-sm-6">
                <label>City</label>
                <div class="form-group">
                  {{form.city}}
                </div>
              </div>
              <div class="col-sm-6">
                <label>State</label>
                <div class="form-group">
                  {{form.state}}
                </div>
              </div>
              <div class="col-sm-6">
                <label>Latitude</label>
                <div class="form-group">
                  {{form.latitude}}
                </div>
              </div>
              <div class="col-sm-6">
                <label>Longitude</label>
                <div class="form-group">
                  {{form.longitude}}
                </div>
              </div>

            </div>
          </div>
          <div class="inner-box">
            <h3 class="inner-item-heading2">Details Information</h3>
            <div class="row">
              <div class="col-sm-12">
                <label>E-mail</label>
                <div class="form-group">
                  {{form.email}}
                </div>
              </div>
              <div class="col-sm-6">
                <label>Phone</label>
                <div class="form-group">
                  {{form.main_phone}}
                </div>
              </div>
              <div class="col-sm-6">
                <label>Mobile Phone</label>
                <div class="form-group">
                  {{form.mobile_phone}}
                </div>
              </div>
            </div>
          </div>
          <div class="inner-box menu-list-wrapper">
            <h3 class="inner-item-heading2">Gallery Images</h3>
            <label>Click here or drope files to upload</label>
            <div class="row menu-list">
              <div class="col-sm-4 col-12 menu-item">
                <div class="form-group">
                  {{form.image1}}
                </div>
              </div>
              <div class="col-sm-4 col-12 menu-item">
                <div class="form-group">
                  {{form.image2}}
                </div>
              </div>
              <div class="col-sm-4 col-12 menu-item">
                <div class="form-group">
                  {{form.image3}}
                </div>
              </div>
              <div class="col-sm-4 col-12 menu-item hidden">
                <div class="form-group">
                  <input class="form-control img-upload-box" id="img-upload4" type="file" />
                </div>
              </div>
              <div class="col-sm-4 col-12 menu-item hidden">
                <div class="form-group">
                  <input class="form-control img-upload-box" id="img-upload5" type="file" />
                </div>
              </div>
              <div class="col-sm-4 col-12 menu-item hidden">
                <div class="form-group">
                  <input class="form-control img-upload-box" id="img-upload6" type="file" />
                </div>
              </div>
              <div class="col-sm-4 col-12 menu-item hidden">
                <div class="form-group">
                  <input class="form-control img-upload-box" id="img-upload7" type="file" />
                </div>
              </div>
              <div class="col-sm-4 col-12 menu-item hidden">
                <div class="form-group">
                  <input class="form-control img-upload-box" id="img-upload8" type="file" />
                </div>
              </div>
              <div class="col-sm-4 col-12 menu-item hidden">
                <div class="form-group">
                  <input class="form-control img-upload-box" id="img-upload9" type="file" />
                </div>
              </div>
            </div>
          </div>
          <div class="inner-box">
            <h3 class="inner-item-heading2">Amenities</h3>
            <div>
              <label>Amenities (Optional)</label>
              <div class="form-group">
               {{ form.amenities }}
              </div>
            </div>
          </div>
          <div class="inner-box">
            <h3 class="inner-item-heading2">Amenities</h3>
            <div>
              <label>Enter the price</label>
              <div class="form-group">
               {{ form.price }}
              </div>
              {{form.errors}}
            </div>
          </div>
          <div class="inner-box">
            <button class="btn-upload" type="submit">UPLOAD NOW</button>
          </div>
          {% if success %}
          <div class="alert alert-success text-center" role="alert" style="margin-top:8px;">
            {{success}}
          </div>
          {% endif %}
        </form>
      </div>
      <div class="col-lg-4 sidebar-widget-area sidebar-break-md">
        <div class="widget widget-box-padding widget-follow-us">
          <h3 class="widget-title">Follow Us</h3>
          <ul class="inline-list">
            {% if context_about.facebook %}
            <li class="single-item"><a href="{{ context_about.facebook }}" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
            {% endif %}
            {% if context_about.twitter %}
                <li class="single-item"><a href="{{ context_about.twitter }}" target="_blank"><i class="fab fa-twitter"></i></a></li>
            {% endif %}
            {% if context_about.linkedin %}
                <li class="single-item"><a href="{{ context_about.linkedin }}" target="_blank"><i class="fab fa-linkedin-in"></i></a></li>
            {% endif %}
            {% if context_about.pinterest %}
                <li class="single-item"><a href="{{ context_about.pinterest }}" target="_blank"><i class="fab fa-pinterest-p"></i></a></li>
            {% endif %}
            {% if context_about.skype %}
                <li class="single-item"><a href="{{ context_about.skype }}" target="_blank"><i class="fab fa-skype"></i></a></li>
            {% endif %}
            {% if context_about.rss %}
                <li class="single-item"><a href="{{ context_about.rss }}" target="_blank"><i class="fas fa-rss"></i></a></li>
            {% endif %}
            {% if context_about.dribble %}
                <li class="single-item"><a href="{{ context_about.dribble }}" target="_blank"><i class="fab fa-dribbble"></i></a></li>
            {% endif %}
            {% if context_about.instagram %}
                <li class="single-item"><a href="{{ context_about.instagram }}" target="_blank"><i class="fab fa-instagram"></i></a></li>
            {% endif %}
            {% if context_about.google_plus %}
                <li class="single-item"><a href="{{ context_about.google_plus }}" target="_blank"><i class="fab fa-google-plus-g"></i></a></li>
            {% endif %}
            {% if context_about.vk %}
                <li class="single-item"><a href="{{ context_about.vk }}" target="_blank"><i class="fab fa-vk"></i></a></li>
            {% endif %}
          </ul>
        </div>
        <div class="widget widget-box-padding widget-poster">
          <div class="item-img">
            <img alt="Poster" class="img-fluid" src="{{ context_ad_image.image.url }}" />
          </div>
        </div>
      </div>
    </div>
  </div>
</section>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
  $(document).ready(function() {
      $('#id_category').change(function() {
        var selectedCategory = $(this).val();
        if (!selectedCategory || selectedCategory === "default") {  // Update "default" to the value of your default category
            $.ajax({
                url: '/listing/get_all_subcategories/',  // Update this URL to the one in your Django project
                success: function(data) {
                    var options = '';
                    for (var i = 0; i < data.length; i++) {
                        options += '<option value="' + data[i].id + '">' + data[i].name + '</option>';
                    }
                    $('#id_subcategory').html(options);
                }
            });
        } else if (selectedCategory) {
              $.ajax({
                  url: '/listing/get_subcategories/',  // Update this URL to the one in your Django project
                  data: {
                      'category': selectedCategory
                  },
                  success: function(data) {
                      var options = '';
                      for (var i = 0; i < data.length; i++) {
                          options += '<option value="' + data[i].id + '">' + data[i].name + '</option>';
                      }
                      $('#id_subcategory').html(options);
                  }
              });
          } else {
              $('#id_subcategory').html('');
          }
      });
  });
</script>

<head>
  {{ form.media }}
</head>


{% endblock main %}